// Flattened from contextMenu/muya.js, contextMenu/sideDrawer.js, contextMenu/markMap.js.
// Generated by _temp/flatten-i18n.js. Do not edit by hand.
export default {
  cut: 'Cut',
  copy: 'Copy',
  paste: 'Paste',
  copyAsMarkdown: 'Copy As Markdown',
  copyAsHtml: 'Copy As HTML',
  pasteAsPlainText: 'Paste As Plain Text',
  insertBefore: 'Insert Before',
  insertAfter: 'Insert After',
  formatDocumentByPangu: 'Format Document',
  generateMindmap: 'Generate Mindmap',
  openTierRanking: 'Tier Ranking (Global)',
  openTierRankingForCategory: 'Tier Ranking',
  openTierRankingForNote: 'Tier Ranking',
  exportToBlog: 'Deploy VuePress Blog',
  copyMarkdown: 'Copy MD to Clipboard',
  copyMarkdownContent: 'Copy Full Content',
  copyNote: 'Copy Note',
  saveAsPNG: 'Save As PNG',
  saveAsSVG: 'Save As SVG',
  saveAsHTML: 'Save As HTML'
}
