export default function () {
  return {
    language: null,
    autoLogin: false,
    rememberPassword: true,
    darkMode: false,
    noteListDenseMode: false,
    markdownOnly: false,
    enableSelfHostServer: false,
    imageUploadService: 'wizOfficialImageUploadService',
    imageUploadServiceParam: {},
    noteOrderType: 'orderByNoteTitle',
    apiServerUrl: '',
    postParam: '',
    jsonPath: '',
    customHeader: '',
    customBody: '',
    shrinkInTray: false,
    paneLayoutMode: 0,
    categoryTreeVisible: true,
    noteListVisible: true,
    enablePreviewEditor: true,
    rightClickNoteItem: {},
    rightClickCategoryItem: '',
    theme: 'Default-Light',
    themes: [],
    autoSaveGap: 0,
    splitterWidth: 580,
    sidebarTreeType: 'category',
    noteMethod: 'notesSixDaoLun',
    noteMethodPrefix: 'Course',
    calendarSelectedDate: '',
    calendarDateBasis: 'modified',
    leftInnerSplitterRatio: 280,
    runeCards: [],
    syncStatus: {
      isSyncing: false,
      lastSyncTime: null,
      total: 0,
      synced: 0,
      pending: 0
    }
  }
}
