export default {
  exportMarkdownFile: 'export-markdown-file',
  exportPng: 'export-png',
  exportFile: 'export-file',
  exportMarkdownFiles: 'export-markdown-files',
  importImage: 'import-image',
  uploadImages: 'upload-images',
  checkUpdate: 'check-update',
  needUpdate: 'need-update',
  quitAndUpdate: 'quit-and-install',
  remoteRequest: 'remote-request',
  getCacheImage: 'get-cache-image',
  saveTempImage: 'save-temp-image',
  loadTheme: 'load-theme',
  openThemeFolder: 'open-theme-folder',
  openLogFiles: 'open-log-files',
  refreshThemeFolder: 'refresh-theme-folder',
  getLocalFileData: 'get-local-file-data',
  saveUploadedImage: 'save-uploaded-image',
  popContextMenu: 'pop-context-menu',
  getAppPath: 'get-app-path',
  startBlogDeploy: 'start-blog-deploy',
  cancelBlogDeploy: 'cancel-blog-deploy',
  getBlogDeployConfig: 'get-blog-deploy-config',
  saveBlogDeployConfig: 'save-blog-deploy-config',
  selectDirectory: 'select-directory',
  // Export CI workflows (.github/workflows/*.yml) to blog directory
  exportBlogCI: 'export-blog-ci',
  // SFTP 部署
  sftpTestConnection: 'sftp-test-connection',
  sftpUpload: 'sftp-upload'
}
