// Flattened from contextMenu/muya.js, contextMenu/sideDrawer.js, contextMenu/markMap.js.
// Generated by _temp/flatten-i18n.js. Do not edit by hand.
export default {
  cut: '剪切',
  copy: '复制',
  paste: '粘贴',
  copyAsMarkdown: '复制 Markdown 文本',
  copyAsHtml: '复制 HTML 文本',
  pasteAsPlainText: '以纯文本形式粘贴',
  insertBefore: '在此之前插入段落',
  insertAfter: '在此之后插入段落',
  formatDocumentByPangu: '格式化文档',
  generateMindmap: '生成思维导图',
  openTierRanking: '从夯到拉（全局）',
  openTierRankingForCategory: '从夯到拉',
  openTierRankingForNote: '从夯到拉',
  exportToBlog: '部署 VuePress 博客',
  copyMarkdown: '复制 MD 到剪贴板',
  copyMarkdownContent: '复制完整内容',
  copyNote: '复制笔记',
  saveAsPNG: '保存为 PNG',
  saveAsSVG: '保存为 SVG',
  saveAsHTML: '保存为 HTML'
}
